package przychodnia;
// Generated 2018-12-29 17:40:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pacjent generated by hbm2java
 */
public class Pacjent  implements java.io.Serializable {


     private Integer idPacjent;
     private String imie;
     private String nazwisko;
     private Date dataUr;

    public Pacjent() {
    }

    public Pacjent(String imie, String nazwisko, Date dataUr) {
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.dataUr = dataUr;
    }
   
    public Integer getIdPacjent() {
        return this.idPacjent;
    }
    
    public void setIdPacjent(Integer idPacjent) {
        this.idPacjent = idPacjent;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public Date getDataUr() {
        return this.dataUr;
    }
    
    public void setDataUr(Date dataUr) {
        this.dataUr = dataUr;
    }




}


