package przychodnia;
// Generated 2018-12-30 17:11:20 by Hibernate Tools 4.3.1



/**
 * Pacjentkarta generated by hbm2java
 */
public class Pacjentkarta  implements java.io.Serializable {


     private PacjentkartaId id;
     private Karta karta;
     private Pacjent pacjent;

    public Pacjentkarta() {
    }

    public Pacjentkarta(PacjentkartaId id, Karta karta, Pacjent pacjent) {
       this.id = id;
       this.karta = karta;
       this.pacjent = pacjent;
    }
   
    public PacjentkartaId getId() {
        return this.id;
    }
    
    public void setId(PacjentkartaId id) {
        this.id = id;
    }
    public Karta getKarta() {
        return this.karta;
    }
    
    public void setKarta(Karta karta) {
        this.karta = karta;
    }
    public Pacjent getPacjent() {
        return this.pacjent;
    }
    
    public void setPacjent(Pacjent pacjent) {
        this.pacjent = pacjent;
    }




}


