package przychodnia;
// Generated 2018-12-30 17:11:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pracownik generated by hbm2java
 */
public class Pracownik  implements java.io.Serializable {


     private Integer idPracownik;
     private String imie;
     private String nazwisko;
     private String rola;
     private Set wizyties = new HashSet(0);

    public Pracownik() {
    }

	
    public Pracownik(String imie, String nazwisko, String rola) {
        this.imie = imie;
        this.nazwisko = nazwisko;
        this.rola = rola;
    }
    public Pracownik(String imie, String nazwisko, String rola, Set wizyties) {
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.rola = rola;
       this.wizyties = wizyties;
    }
   
    public Integer getIdPracownik() {
        return this.idPracownik;
    }
    
    public void setIdPracownik(Integer idPracownik) {
        this.idPracownik = idPracownik;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public String getRola() {
        return this.rola;
    }
    
    public void setRola(String rola) {
        this.rola = rola;
    }
    public Set getWizyties() {
        return this.wizyties;
    }
    
    public void setWizyties(Set wizyties) {
        this.wizyties = wizyties;
    }




}


