package przychodnia;
// Generated 2018-12-30 17:11:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Wizyty generated by hbm2java
 */
public class Wizyty  implements java.io.Serializable {


     private Integer idWizyty;
     private Pacjent pacjent;
     private Pracownik pracownik;
     private Date dataWiz;

    public Wizyty() {
    }

    public Wizyty(Pacjent pacjent, Pracownik pracownik, Date dataWiz) {
       this.pacjent = pacjent;
       this.pracownik = pracownik;
       this.dataWiz = dataWiz;
    }
   
    public Integer getIdWizyty() {
        return this.idWizyty;
    }
    
    public void setIdWizyty(Integer idWizyty) {
        this.idWizyty = idWizyty;
    }
    public Pacjent getPacjent() {
        return this.pacjent;
    }
    
    public void setPacjent(Pacjent pacjent) {
        this.pacjent = pacjent;
    }
    public Pracownik getPracownik() {
        return this.pracownik;
    }
    
    public void setPracownik(Pracownik pracownik) {
        this.pracownik = pracownik;
    }
    public Date getDataWiz() {
        return this.dataWiz;
    }
    
    public void setDataWiz(Date dataWiz) {
        this.dataWiz = dataWiz;
    }




}


